Feature/jfas/environment warning history clean
AnalogIO/coffeecard_app pull request #205
Opened 2022-03-13 17:17 UTC by jonasanker

Closes #158 

Cleanup of dirty commit history in #181

2022-03-13 21:03 UTC, Jens-Fastrup commented
Having issues on this branch (as well as origin/develop) loading MobilePay reciepts, stats, settings. Set up the mobilepay test app with login(nr, pin, cpr)  but still does not bother. What did I miss (also did a full run build)?

2022-03-13 21:20 UTC, TTA777 commented
> Having issues on this branch (as well as origin/develop) loading MobilePay reciepts, stats, settings. Set up the mobilepay test app with login(nr, pin, cpr) but still does not bother. What did I miss (also did a full run build)?

Since this is a bit light on details, I'll give guess, but I am not sure. If it is everything that you are unable to load data from, try logging out of the app. If you are unable to access the log out button on the settings page, due to this page not loading, you can clear the apps data cache using the android settings. 

I'm guessing what has happened is you were signed in to another backend previously, so your app still thinks you are signed in, since it still has a token cached, which is what we now want to clear.

2022-03-13 21:24 UTC, Jens-Fastrup commented
Sounds very plausible! Will try those steps

2022-03-14 07:57 UTC, marfavi commented
Will review

2022-03-14 10:39 UTC, fremartini commented on lib/cubits/environment/environment_state.dart
> +class EnvironmentInitial extends EnvironmentState {}
change to EnvironmentLoading to stay consistent with other states?

2022-03-15 21:08 UTC, marfavi requested changes

2022-03-15 21:08 UTC, marfavi commented on lib/widgets/components/receipt/receipt_overlay.dart
> +        return Center(
Seems like the padding that should wrap this widget is removed.

2022-03-15 21:09 UTC, marfavi commented on lib/widgets/components/receipt/receipt_overlay.dart
> +        return Center(
![image](https://user-images.githubusercontent.com/21163286/158472972-f3db4742-dd0a-4fa9-b65a-ca51045e95e5.png)

2022-03-18 10:22 UTC, fremartini commented
@Jens-Fastrup can you have a look at finishing this one?

2022-03-18 10:47 UTC, Jens-Fastrup commented
@fremartini , spoke with @marfavi today who will add the padding as I have issues with building the app on my desktop. He will likely resolve it soon

2022-03-18 11:24 UTC, marfavi commented
Added padding & made it more responsive as well (less padding on smaller screens)
![image](https://user-images.githubusercontent.com/21163286/158994653-b013c85b-2a99-41f6-bb89-b670d9a2f499.png)

2022-03-18 11:25 UTC, marfavi approved these changes

2022-03-18 11:28 UTC, merged