Firebase Crashlytics, Analytics and Performance setup
AnalogIO/coffeecard_app pull request #315
Opened 2022-05-30 23:11 UTC by jonasanker

Closing #25

2022-05-30 23:28 UTC, jonasanker commented on lib/payment/mobilepay_service.dart
> +          productId: purchaseResponse.productId,
Backend must provide product name

2022-05-30 23:54 UTC, jonasanker commented
More Analytics logs to be added
- view_item
- view_item_list
- select_item

2022-05-31 11:25 UTC, jonasanker commented on lib/payment/mobilepay_service.dart
> +          productId: purchaseResponse.productId,
Resolved in https://github.com/AnalogIO/analog-core/pull/89

2022-05-31 21:09 UTC, marfavi requested changes
Static analysis still failing

2022-05-31 21:23 UTC, jonasanker commented
> Static analysis still failing

@marfavi Fixed

2022-05-31 21:44 UTC, marfavi requested changes

2022-05-31 21:44 UTC, marfavi commented on lib/cubits/login/login_cubit.dart
> +    sl<FirebaseAnalyticsEventLogging>().loginEvent();
User hasn't logged in at this point yet. Line should be moved down to around line 60

2022-05-31 21:44 UTC, marfavi commented on lib/cubits/register/register_cubit.dart
> +    sl<FirebaseAnalyticsEventLogging>().signUpEvent();
Should be below the if clause (to prevent firing a sign up event in the case of an unsuccessful registration).

2022-05-31 21:44 UTC, marfavi commented on pubspec.yaml
> +  firebase_core: ^1.17.1
add a comment heading to separate it from the "brightness" category

2022-05-31 21:48 UTC, jonasanker commented
@marfavi Code review comments have been fixed

2022-05-31 21:49 UTC, marfavi approved these changes
OK

2022-05-31 22:03 UTC, merged