Show barista hub if user is barista+
AnalogIO/coffeecard_app pull request #413
Opened 2023-03-28 18:34 UTC by fredpetersen

2023-04-11 15:22 UTC, fremartini commented on lib/cubits/user/user_cubit.dart
> +      emit(UserInitiallyLoaded(st));
if (state is UserLoaded) { emit(UserInitiallyLoaded(state)); } ?

2023-04-11 15:23 UTC, fremartini commented on lib/models/ticket/ticket_count.dart
> +const _baristaProductIds = [9, 11, 12, 13];
??????

2023-04-11 15:24 UTC, fremartini commented on lib/utils/user_group_permissions.dart
> +  switch (user.userGroup) {
return user.userGroup in [UserGroup.Barista, ..., ... ,], default false

2023-04-11 15:25 UTC, fremartini commented on lib/widgets/components/tickets/tickets_section.dart
> +    return _TicketSection(filter: (ticket) => ticket.isBaristaTicket());
why underscore?

2023-10-19 13:50 UTC, marfavi requested changes
Half-review so we know what to work on next

2023-10-19 13:50 UTC, marfavi commented on lib/core/widgets/components/barista_perks_section.dart
> +          children: [
List should not be hardcoded but rather based on perks available to the user

2023-10-19 13:50 UTC, marfavi commented on lib/core/widgets/pages/home_page.dart
> +  List<AppFlow> get _bottomNavAppFlows => <AppFlow>[
Why was this moved up the file?

2023-10-19 13:50 UTC, marfavi commented on lib/data/repositories/barista_product/barista_product_repository.dart
> +    // TODO(fredpetersen): Replace with data fetch from backend, https://github.com/AnalogIO/coffeecard_app/issues/422
Work on this TODO

2023-10-19 13:50 UTC, marfavi commented on lib/features/product/data/models/product_model.dart
> +      isPerk: false, // TODO Integrate with backend
Work on this TODO

2023-10-19 13:52 UTC, marfavi commented
I'd suggest to move the "loading the user in the splash screen " functionality into its own PR to speed things up

2023-10-24 15:50 UTC, marfavi commented on ios/Podfile
> +      xcconfig_path = config.base_configuration_reference.real_path
Done

2023-10-24 15:52 UTC, marfavi commented on lib/base/style/text_styles.dart
> +
Done

2023-10-24 22:15 UTC, marfavi commented
> I'd suggest to move the "loading the user in the splash screen " functionality into its own PR to speed things up

Done via #528

2023-10-26 15:50 UTC, fredpetersen commented on lib/core/strings.dart
> -  static const cofeeCardTicketsLeft = 'Tickets left:';
It is unused, i dont want to create a seperate PR for this one line :)

2023-10-26 18:32 UTC, marfavi commented on lib/core/widgets/components/barista_indicator.dart
> +        title: userRole.name, // TODO(fredpetersen): Should be capitalized
use `.capitalize()` extension method to do this

2023-10-26 18:32 UTC, marfavi commented on lib/core/widgets/components/barista_indicator.dart
> +            userRole.name, // TODO(fredpetersen): Should be capitalized
use .capitalize() extension method to do this

2023-11-09 18:46 UTC, marfavi reviewed
Looks good

2023-11-09 19:02 UTC, marfavi approved these changes

2023-11-09 19:14 UTC, marfavi approved these changes

2023-11-09 19:24 UTC, merged