Remove ReceiptOverlay and AmountPurchased dependency
AnalogIO/coffeecard_app pull request #423
Opened 2023-04-18 17:51 UTC by fremartini

closes #384

2023-04-23 19:36 UTC, TTA777 requested changes
Minor changes requested

2023-04-23 19:36 UTC, TTA777 commented on test/features/ticket/presentation/cubit/tickets_cubit_test.dart
> +      'should emit [Using, Error Loaded] when state is Loaded',
Missing ',' between Error and Loaded?

2023-04-23 19:42 UTC, fremartini commented on lib/features/receipt/presentation/widgets/receipt_list_entry_factory.dart
> +  static Widget create(Receipt receipt) {
no, I don't believe a factory implementation would work. See payment_handler for a similar implimentation; the list_entry widgets also don't inherit from receipt_list_entry so  you can't use a factory here

2023-04-24 10:05 UTC, TTA777 approved these changes
Lgtm for now. Just need to rebase, and fix any of the errors the new linter gives you

2023-04-24 10:05 UTC, merged