Tidy up settings page
AnalogIO/coffeecard_app pull request #473
Opened 2023-05-24 01:14 UTC by marfavi

2023-05-24 01:16 UTC, marfavi commented on lib/widgets/pages/settings/settings_page.dart
> +  const SettingsPage._({required this.scrollController});
Private constructor to convey that `SettingsPage.routeWith` should be used to navigate to this page.

2023-05-26 16:04 UTC, fremartini requested changes

2023-05-26 21:38 UTC, marfavi commented on lib/widgets/pages/settings/settings_page.dart
> +class _ProfileSection extends StatelessWidget {
That's out of scope for this PR. I was simply trying to fix the TODO that was present in the top of this file.

Keep in mind that all these "new" widgets were already in the file. Now, they are extracted into smaller widgets. In another PR, we may extract them even further and transition them into the feature file structure as you describe

2023-05-27 06:29 UTC, fremartini approved these changes

2023-05-27 06:56 UTC, merged