refactor and test voucher
AnalogIO/coffeecard_app pull request #480
Opened 2023-05-27 06:49 UTC by fremartini

2023-05-27 22:07 UTC, marfavi requested changes

2023-05-27 22:07 UTC, marfavi commented on test/features/voucher/data/datasources/voucher_remote_data_source_test.dart
> +    test('should call executor', () async {
test name and assertion step differ ("Should call executor" would check if executor was called in the assertion step)

2023-05-28 06:34 UTC, marfavi submitted a review, later dismissed

2023-05-28 06:45 UTC, marfavi submitted a review, later dismissed
If you use the 'Update branch' button on GitHub, you won't invalidate any reviews :)

2023-05-28 06:55 UTC, fremartini commented
@marfavi merged develop again. Can't Update Branch from here because merge conflicts

2023-05-28 06:56 UTC, marfavi approved these changes
All good

2023-05-28 07:09 UTC, merged